name: Windows i686

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        release: false
        update: false
        install: >-
          base-devel
          git
          mingw-w64-i686-gcc
          mingw-w64-i686-SDL2
          mingw-w64-i686-SDL2_image
          mingw-w64-i686-SDL2_net
          mingw-w64-i686-libarchive
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - shell: msys2 {0}
      run: |
        make -j 4
        cp BUILD/PokittoEmu.exe ./
        cp /mingw32/bin/libgcc_s_dw2-1.dll ./
        cp /mingw32/bin/libstdc++*.dll ./
        cp /mingw32/bin/libpng*.dll ./
        cp /mingw32/bin/SDL2_image.dll ./
        cp /mingw32/bin/SDL2_net.dll ./
        cp /mingw32/bin/SDL2.dll ./
        cp /mingw32/bin/zlib1.dll ./
        cp /mingw32/bin/libwebp*.dll ./
        cp /mingw32/bin/libjxl*.dll ./
        cp /mingw32/bin/libjpeg*.dll ./
        cp /mingw32/bin/libtiff*.dll ./
        cp /mingw32/bin/libdeflate.dll ./
        cp /mingw32/bin/libjbig*.dll ./
        cp /mingw32/bin/libLerc.dll ./
        cp /mingw32/bin/libzstd.dll ./
        cp /mingw32/bin/liblzma*.dll ./
        cp /mingw32/bin/libwinpthread*.dll ./
        cp /mingw32/bin/libbrotli*.dll ./
        cp /mingw32/bin/liblcms*.dll ./
        cp /mingw32/bin/libhwy*.dll ./
        cp /mingw32/bin/libarchive*.dll ./
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pokittoemu-windows-i686
        path: |
          PokittoEmu.exe
          *.dll
