name: Emscripten

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "emscripten"
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: mymindstorm/setup-emsdk@v11
    - name: make
      run: make -j 4 -f Makefile.wasm
    - name: Copy Files
      run: cp -r ONLINE/* emscripten/
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: 'emscripten'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
